name: Run Tests
on:
  push:
    branches: [ "*" ]
    tags: [ "*" ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go-version: ['1.23.5']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Install libwebp on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libwebp-dev

      - name: Install libwebp on macOS
        if: matrix.os == 'macos-latest'
        run: brew install webp

      - name: Install libwebp on Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          curl -L https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.3.2-windows-x64.zip -o libwebp.zip
          unzip libwebp.zip -d libwebp
          # Get the current working directory (repository root)
          $pwd = Get-Location
          # Set CGO_CFLAGS and CGO_LDFLAGS using the extracted folder's path
          echo "CGO_CFLAGS=-I$($pwd)\libwebp\libwebp-1.3.2-windows-x64\include" | Out-File -Append -FilePath $env:GITHUB_ENV
          echo "CGO_LDFLAGS=-L$($pwd)\libwebp\libwebp-1.3.2-windows-x64\lib -lwebp" | Out-File -Append -FilePath $env:GITHUB_ENV

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        shell: bash
        run: go test -v ./...
